// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

export const firebaseConfig = {
  "apiKey": "AIzaSyBGz8j572klRVWrvgKrfr9Gkpb5v2coGBc",
  "authDomain": "studio-2680655679-36c60.firebaseapp.com",
  "projectId": "studio-2680655679-36c60",
  "storageBucket": "studio-2680655679-36c60.appspot.com",
  "messagingSenderId": "698672764159",
  "appId": "1:698672764159:web:c796c6f87bfc3e6b8ea8ca",
  "measurementId": "G-S0X2TTCY1Y"
};
