
'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import type { Assessment, ValuationResult } from '@/types';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { calculateValuation } from '@/lib/valuation-engine';
import { ArrowLeft, Check, Loader2, ServerCrash, X } from 'lucide-react';
import { Card, CardContent } from '../ui/card';

type ValuationStepProps = {
  onNext: (data: Partial<Assessment>) => void;
  onBack: () => void;
  onRestart: () => void;
  data: Assessment;
  lang: 'en' | 'fr';
};

const content = {
    en: {
        title: "AI Valuation",
        calculatingTitle: "AI Analyzing & Calculating Offer...",
        calculatingDescription: "Our AI is analyzing your vehicle's condition and data to generate your custom valuation.",
        errorTitle: "Valuation Error",
        aiSummaryTitle: "AI Condition Summary",
        breakdownTitle: "Valuation Breakdown",
        breakdown: {
            metalValue: "Metal Value",
            partsValue: "Parts Value",
            classBonus: "Class Bonus",
            penalties: "Penalties",
            completeBonus: "Complete Bonus",
        },
        towingFree: "GOOD NEWS, TOWING IS FREE!",
        backButton: "Back",
        acceptButton: "Accept",
        refuseButton: "Refused",
        finalOfferTitle: "Automatically Calculated Offer:",
        finalOfferDescription: "Offer generated by Car Scrap AI in real-time."
    },
    fr: {
        title: "Évaluation IA",
        calculatingTitle: "Analyse et calcul de l'offre en cours...",
        calculatingDescription: "Notre IA analyse l'état de votre véhicule pour générer une évaluation personnalisée.",
        errorTitle: "Erreur d'évaluation",
        aiSummaryTitle: "Résumé de l'état par l'IA",
        breakdownTitle: "Détails de l'évaluation",
        breakdown: {
            metalValue: "Valeur du métal",
            partsValue: "Valeur des pièces",
            classBonus: "Bonus de classe",
            penalties: "Pénalités",
            completeBonus: "Bonus véhicule complet",
        },
        towingFree: "BONNE NOUVELLE, LE REMORQUAGE EST GRATUIT !",
        backButton: "Retour",
        acceptButton: "Accepter",
        refuseButton: "Refuser",
        finalOfferTitle: "Offre calculée automatiquement :",
        finalOfferDescription: "Offre générée par Car Scrap AI en temps réel."
    }
}

export function ValuationStep({ onNext, onBack, onRestart, data, lang }: ValuationStepProps) {
  const c = content[lang];
  const [loading, setLoading] = useState(true);
  const [valuation, setValuation] = useState<ValuationResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const getValuation = async () => {
      if (!data.condition) {
        setError("Condition data is missing.");
        setLoading(false);
        return;
      }
      
      setLoading(true);
      setError(null);
      
      setTimeout(() => {
        try {
          const valuationResult = calculateValuation(data);
          setValuation(valuationResult);
        } catch (e: any) {
          console.error("Valuation Error:", e);
          setError(e.message || 'The valuation could not be completed. Please try again.');
        } finally {
          setLoading(false);
        }
      }, 3000);
    };

    getValuation();
  }, [data]);

  const handleAccept = () => {
    if (valuation) {
      onNext({ valuation });
    }
  };
  
  return (
    <div className="h-full flex flex-col p-6 items-center justify-center">
      <Card className="max-w-md w-full text-center shadow-lg p-4">
        <CardContent className="pt-6">
          <h2 className="text-2xl font-semibold mb-4 font-headline">{c.title}</h2>

          {loading && (
            <div className="flex flex-col items-center space-y-2">
              <Loader2 className="animate-spin text-primary w-8 h-8" />
              <p className="text-muted-foreground">{c.calculatingTitle}</p>
            </div>
          )}

          {error && (
             <Alert variant="destructive" className="max-w-md">
               <ServerCrash className="h-4 w-4" />
               <AlertTitle>{c.errorTitle}</AlertTitle>
               <AlertDescription>{error}</AlertDescription>
             </Alert>
          )}

          {!loading && !error && valuation && (
            <div className="animate-in fade-in duration-500">
              <p className="text-lg text-muted-foreground mb-2">
                {c.finalOfferTitle}
              </p>
              <h3 className="text-4xl font-bold text-primary">
                💰 {valuation.finalPrice} $
              </h3>
              <p className="text-sm text-muted-foreground mt-2">
                {c.finalOfferDescription}
              </p>
               <p className="text-sm text-green-600 font-bold mt-4 animate-pulse">
                {c.towingFree}
            </p>
            </div>
          )}
        </CardContent>
      </Card>

      <div className="flex flex-col sm:flex-row justify-between items-center pt-6 mt-6 w-full max-w-md gap-3">
        <Button type="button" variant="outline" onClick={onBack} disabled={loading} className="w-full sm:w-auto order-3 sm:order-1">
          <ArrowLeft className="mr-2 h-4 w-4" />
          {c.backButton}
        </Button>
        <div className="flex gap-2 w-full sm:w-auto order-1 sm:order-2">
             <Button type="button" variant="destructive" onClick={onRestart} disabled={loading} className="flex-1">
                <X className="mr-2 h-4 w-4" />
                {c.refuseButton}
            </Button>
            <Button type="button" onClick={handleAccept} disabled={loading || !valuation} className="bg-green-600 hover:bg-green-700 text-white flex-1">
                <Check className="mr-2 h-4 w-4" />
                {c.acceptButton}
            </Button>
        </div>
      </div>
    </div>
  );
}
